### ISSUE TITLE
Edge NGram unexpected output

### ISSUE THREAD

**Issue by interlark** [blevesearch/beer-search#15]
![image](https://user-images.githubusercontent.com/20641837/126229588-d49b6d9a-c105-4973-91a7-7da11ddaa39f.png)
I've added n-gram token analyzer on `"description"` field. It outputs strange results. I mean, for the input `"brew durin"` how come it gives score of `"brettanomyces. During"` bigger than next `"brewed during"` ?

**Comment by interlark** [comment]
Parametes for `edge_ngram: { min:1, max:20 }`, with `min:2` everything works fine. Looks like the `ngram token's filter` bug with `min: 1`. What do you think?
[mapping.zip](https://github.com/blevesearch/beer-search/files/6844053/mapping.zip)

**Comment by interlark** [comment]
And why result score is inconsistent? I've recorded a screencast for you so you can see the score of 2 bottom items changes from time to time, why?
![Peek 2021-07-20 02-48](https://user-images.githubusercontent.com/20641837/126231909-2d8710a3-2202-45a1-b94a-b1f47dc4c905.gif)

**Comment by mschoch** [comment]
Can you share the changes you made to the beer-search code to use edge ngram?  I'd like to be able to reproduce what you're doing here.

**Comment by interlark** [comment]
Here's my mappings, the only file I changed:
[mapping.zip](https://github.com/blevesearch/beer-search/files/6846015/mapping.zip)
Another nondeterministic behavior:
![Peek 2021-07-20 11-40](https://user-images.githubusercontent.com/20641837/126274041-65e0330d-d203-42a8-add6-c6f14b5c6110.gif)

**Comment by mschoch** [comment]
So, regarding your first question.  The phrase search just finds tokens that match the phrase and positional requirements.  Because the ngram analyzers generate a lot of tokens, these weaker single letter matches are also included.  Finally, each of these term matches is scored independently based on the tf-idf ranking (which is meaningless on the ngram output).  So in short the phrase "b d" will match and so will the exact "brew during" and which one ranks higher depends on the the tf-idf details.  If you wanted longer matches to score better here, you'd have to write code for that as it isn't supported today.

Next, regarding the inconsistent behavior, that is more trouble and I'm still looking into why it is happening.  But, I am able to reproduce it locally.

**Comment by mschoch** [comment]
Here is the output from the analysis wizard, so it looks like the tokens generated are correct, at least in this case:

![Bleve-Text-Analysis-Wizard](https://user-images.githubusercontent.com/298143/126328633-65bd12c3-7d5b-483a-a8da-e29e6138e690.png)

**Comment by mschoch** [comment]
So, what I'm able to observe is that most requests return 220 total hits (and the top 10 appear correct).  However, once very few requests, instead 1113 hits are found.  Closer inspection of these results show that documents are ONLY matching one of the terms "brew".  The scoring explanation shows the coordination factor is 1/1, suggesting perhaps the query executed was wrong.

I'll continue to investigate.

**Comment by mschoch** [comment]
OK, some progress tracking this down.  Here:

https://github.com/blevesearch/bleve/blob/master/search/query/match_phrase.go#L81

we take the input phrase and analyze it.  For some reason, we see different behavior here.  The normal correct case is:

```
2021/07/20 09:30:36 analyze 'brew during' got tokens: [Start: 0  End: 4  Position: 1  Token: b  Type: 0 Start: 0  End: 4  Position: 1  Token: br  Type: 0 Start: 0  End: 4  Position: 1  Token: bre  Type: 0 Start: 0  End: 4  Position: 1  Token: brew  Type: 0 Start: 5  End: 11  Position: 2  Token: d  Type: 0 Start: 5  End: 11  Position: 2  Token: du  Type: 0 Start: 5  End: 11  Position: 2  Token: dur  Type: 0 Start: 5  End: 11  Position: 2  Token: duri  Type: 0 Start: 5  End: 11  Position: 2  Token: durin  Type: 0 Start: 5  End: 11  Position: 2  Token: during  Type: 0]
```
Except, sometimes instead the analysis produces only:

```
2021/07/20 09:30:37 analyze 'brew during' got tokens: [Start: 0  End: 4  Position: 1  Token: brew  Type: 0]
```

All the rest of the weird results are explained by this generating the wrong query sometimes.

**Comment by mschoch** [comment]
Oh wait, I know what is happening.  The mapping defines 2 different types "beer" and "brewery".  Unfortunately, when you use index definitions like this, if you define the same field name for both types, you're likely to encounter problems if you search across them.

Specifically at search time, we see the user referred to the field named "description".  But, unfortunately that is not unique, both beers and breweries have a field with that name, and crucially they have different analyzers.  All bleve does is simply choose one, and which one we get is random.  As a result, sometimes the query is analyzed using the `englishTextFieldMapping` which is set for the brewery type.

So, to fix this problem, you should either change BOTH description fields to use the edge ngram.  Or, you should rename one of the fields so that they are unique.

Let me know if this isn't clear.

**Comment by mschoch** [comment]
Oh wait, I know what is happening.  The mapping defines 2 different types "beer" and "brewery".  Unfortunately, when you use index definitions like this, if you define the same field name for both types, you're likely to encounter problems if you search across them.

Specifically at search time, we see the user referred to the field named "description".  But, unfortunately that is not unique, both beers and breweries have a field with that name, and crucially they have different analyzers.  All bleve does is simply choose one, and which one we get is random.  As a result, sometimes the query is analyzed using the `englishTextFieldMapping` which is set for the brewery type.

So, to fix this problem, you should either change BOTH description fields to use the edge ngram.  Or, you should rename one of the fields so that they are unique.

Let me know if this isn't clear.
