### ISSUE TITLE
Index size 100 X the size of the original data set

### ISSUE THREAD

**Issue by hubyhuby** [blevesearch/beer-search#5]
I have installed and run the example program.
The data set in /data is 2,5MB
After running the example the folder "beer-search.bleve" includes a generated index "store" of 211MB

I would like to use Bleve on 100 Gb of datas...this would mean a  10 TB index !!!
I am new to search engines, so excuse my question: isn t an index supposed to be much smaller than the data set ?

I have googled around and found this explanation from one year ago :+1: https://groups.google.com/forum/#!topic/bleve/xTxlOkTWrLQ

Are those statement still correct ? Is a search engine generating such big indexes is viable ?

**Comment by mschoch** [comment]
That's correct.  You can tune some things to trim down the fat a bit.  I have never seen 100x myself, but even with everything trimmed down it is at least 4x.

No, a search index generating such big index is not viable.

**Comment by hubyhuby** [comment]
Ho Marty, 
Thanks for your super fast answer!
I just read that 4X the original size is something common aswell.
The 100X I get with the "beer example" seams very out of the norm;)
But the exemple seams to be running all well, the 7 000 files are indexed...the search engine runs...
I am on Linux Ubuntu 17.04

![screenshot at 2017-08-18 19-22-07](https://user-images.githubusercontent.com/26340942/29470035-1c2358b4-844b-11e7-98ca-5637b4e97a6e.png)

**Comment by mschoch** [comment]
The main savings will come from turning off stored fields, if you're just using it as an index and not primary storage.  You lose search result highlighting, but you can still do that client-side if you need it.  Further reductions come from not indexing fields you don't want to search on, in particular dates and numbers, as by default those get indexed for range queries, which will index 16 terms for each value.  That makes range searches fast, but waste of space if you don't (some numbers and dates lend themselves more to exact matches rather than ranges anyway).

Finally, as indicated in the message you linked to, greater reductions will have to come from a new index format, most likely one that can't fit into the key/value abstraction.  This is in the design phase, no code to show for it yet...

**Comment by terokarvinen** [comment]
Seems to work for me. 

My Bleve beer-search storage takes less than half of the size of data/ directory. Running beer-search, I have 

  $ du -m data beer-search.bleve/
  30      data
  12      beer-search.bleve/store
  12      beer-search.bleve/

Is this bug from 2017 fixed now, or am I seeing something else?

**Comment by hubyhuby** [comment]
Closed with scorch index
